<a href="https://colab.research.google.com/github/rektyyy/Artificial-Inteligence/blob/main/WarsztatAI/Lista2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

dodaj info o 1pkt za zrobienie na prawdziwym obrazku.
popraw zadania o copy

# Lista 2

## Numpy podstawy

(9pkt + 3pkt)

Na liście znajduje się 9 zadań do wykonania w trakcie zajęć. Po rozwiązaniu zadania pokaż kod prowadzącemu i odpowiedz na **pytanie kontrolne** (są one podane przy każdym zadaniu) — wtedy przyznajemy punkt. Dodatkowo prześlij zadanie na platformie skos.

Jeśli w poleceniu nie jest wskazane użycie pętli `for` - nie korzystaj z niej.

Zadania dodatkowe są oznaczone ⭐️. To zadani o numerach 10 i 11. Dodatkowo moeżesz otrzymać 1pkt z puli punktów bonusowych jeśli wykonasz wszystkie poniższe zadania związane z obrazami na prawdziwym obrazku.

Kazde zadnanie warte jest 1pkt.

## 1. Analiza pikseli obrazu

**Kontekst:** W AI obrazy to tablice NumPy (np. `H×W×C`). Proste operacje na obrazach można robić wektorowo bez pętli.

**Polecenie**

* Utwórz przykładową tablicę 3×3 obrazu RGB zawierającą wartości 0–255.
* Zwiększ jasność o 10% — ale **nie przekraczaj 255** (`np.clip`).
* Pokaż wynik i typ danych.

**Podpowiedź**
Zwiększ jasność obrazu mnożąc każde pasmo RGB przez 110%.

In [ ]:
import numpy as np

A = np.random.randint(0, 256, size=(3, 3, 3))

bright = np.clip(A * 1.10, 0, 255)

print("Oryginał:\n", A)
print("Po zwiększeniu jasności o 10%:\n", bright)

Oryginał:
 [[[189   4 200]
  [  8 243 222]
  [ 13 214   7]]

 [[172  13 202]
  [137 149  66]
  [199  57  79]]

 [[ 30 242 107]
  [ 85  80 125]
  [248 157  40]]]
Po zwiększeniu jasności o 10%:
 [[[207.9   4.4 220. ]
  [  8.8 255.  244.2]
  [ 14.3 235.4   7.7]]

 [[189.2  14.3 222.2]
  [150.7 163.9  72.6]
  [218.9  62.7  86.9]]

 [[ 33.  255.  117.7]
  [ 93.5  88.  137.5]
  [255.  172.7  44. ]]]


## 2. Normalizacja danych wejściowych

**Kontekst:** Dane wejściowe do modeli zazwyczaj normujemy — albo do `[0,1]`, albo standaryzujemy do średniej 0 i odchylenia 1.

**Polecenie**

* Wygeneruj 1D tablicę 100 losowych liczb w przedziale `0..255`.
* Przeskaluj na `[0,1]`.
* Następnie stwórz znormalizowaną wersję z średnią 0 i odchyleniem 1 (standaryzacja).
* Nie używaj pętli.

**Pytanie kontrolne:** Co się stanie, gdy `std == 0`?

In [ ]:
import numpy as np

x = np.random.randint(0, 256, 100)

# skalowanie do [0,1]
x_scaled = x / 255

# standaryzacja: (x - mean)/std
mean = x_scaled.mean()
std = x_scaled.std()
x_standardized = (x_scaled - mean) / std

print("mean scaled:", mean)
print("mean standardized:", x_standardized.mean())
print("std standardized:", x_standardized.std())

mean scaled: 0.5118823529411765
mean standardized: 5.440092820663267e-17
std standardized: 1.0


## 3. Wycinanie fragmentów danych

**Kontekst:** Często dzielimy długi sygnał na krótsze okna (np. do ekstrakcji cech).

**Polecenie**

* Stwórz 1D tablicę długości 1000 (np. `np.arange(1000)`).
* Podziel ją na 10 fragmentów po 100 elementów (`reshape`).
* Oblicz średnią każdego fragmentu (wektor 10-elementowy).

**Pytanie kontrolne:** Co policzymy jeśli obliczymy `axis=0`?

In [ ]:
import numpy as np

x = np.arange(1000)
chunks = x.reshape((10, 100)) # shape (10,100)
means = chunks.mean(axis=1)   # średnia wzdłuż kolumn -> 10 wartości

print("shape chunks:", chunks.shape)
print("means:", means)

shape chunks: (10, 100)
means: [ 49.5 149.5 249.5 349.5 449.5 549.5 649.5 749.5 849.5 949.5]


## 4. Operacje wzdłuż osi

**Kontekst:** Przy normalizacjach i agregacjach często operujemy wzdłuż konkretnej osi.

**Polecenie**

* Utwórz `X = np.random.randint(0, 100, (5,4))`.
* Oblicz:

  * min każdego wiersza używając `X.min(...)`
  * max każdej kolumny używając `X.max(...)`
* Znormalizuj każdy wiersz tak, aby suma elementów w wierszu była równa 1. Sprawdź poprawność rozwiązania sumując wartości w każdym wierszu.

In [ ]:
import numpy as np

X = np.random.randint(0, 100, (5, 4))

row_mins = X.min(axis=1)
col_maxs = X.max(axis=0)

# normalizacja wierszy do sumy 1
row_sums = X.sum(axis=1, keepdims=True)  # shape (5,1) - jakiego parametru trzeba użyć?
X_norm = X / row_sums

print("X:\n", X)
print("row_mins:", row_mins)
print("col_maxs:", col_maxs)
print("X_norm (suma wiersza):", X_norm.sum(axis=1))

X:
 [[50 68 21  8]
 [23 66 27 69]
 [18 37  2 27]
 [26 66 11  9]
 [ 2 17 53 35]]
row_mins: [ 8 23  2  9  2]
col_maxs: [50 68 53 69]
X_norm (suma wiersza): [1. 1. 1. 1. 1.]


## 5. Analiza embeddingów słów

**Kontekst:** W NLP słowa reprezentujemy wektorami (embeddingi). Często chcemy średnią reprezentację zdania i podobieństwo kosinusowe.

**Polecenie**

* Stwórz macierz `E` o kształcie `(5,50)` — 5 embeddingów po 50 wymiarów (`np.random.randn`).
* Oblicz:

  * `mean_embedding` (średni wektor po wierszach)
  * macierz podobieństw kosinusowych między wszystkimi parami wektorów (5×5)

**Pytanie kontrolne:** Jak interpretujesz wartości w `cosine_sim` (zakres i znaczenie)?

---

### Wskazówka

Zastanów się, jak można obliczyć **podobieństwo kosinusowe** dwóch wektorów `a` i `b`, jeśli wiesz, że:

$$
\cos(\theta) = \frac{a \cdot b}{|a| \cdot |b|}
$$

Spróbuj najpierw policzyć to dla jednej pary wektorów w NumPy,
używając `np.dot()` i `np.linalg.norm()`.

A następnie pomyśl:

* Jak znormalizować wszystkie wektory jednocześnie, żeby każdy miał długość 1?
* Jak wykorzystać mnożenie macierzy (`@`), żeby w jednym kroku dostać podobieństwa między wszystkimi parami wektorów (5×5)?

In [ ]:
import numpy as np

E = np.random.randn(5, 50)

# średni wektor (embedding zdania)
mean_embedding = E.mean(axis=0)

# normalizacja wektorów do długości 1
norms = np.linalg.norm(E, axis=1, keepdims=True)
E_normalized = E / norms

# macierz podobieństw kosinusowych = E_norm @ E_norm.T
cosine_sim = E_normalized @ E_normalized.T

print("mean_embedding shape:", mean_embedding.shape)
print("cosine_sim shape:", cosine_sim.shape)
print("cosine_sim (przykład):\n", cosine_sim)

mean_embedding shape: (50,)
cosine_sim shape: (5, 5)
cosine_sim (przykład):
 [[ 1.00000000e+00  1.10991266e-02  9.81479673e-02 -6.15968066e-04
   2.02550599e-01]
 [ 1.10991266e-02  1.00000000e+00  3.83308017e-02 -1.46431847e-01
   1.92687953e-02]
 [ 9.81479673e-02  3.83308017e-02  1.00000000e+00 -3.55297785e-01
   5.53982922e-02]
 [-6.15968066e-04 -1.46431847e-01 -3.55297785e-01  1.00000000e+00
   1.08573275e-01]
 [ 2.02550599e-01  1.92687953e-02  5.53982922e-02  1.08573275e-01
   1.00000000e+00]]


## 6. Sklejanie sensorów — dane z pojazdu autonomicznego

**Kontekst:** Dane z różnych sensorów różnią się formatem — trzeba je połączyć w jedną macierz cech.

**Polecenie**

* Stwórz:

  ```python
  lidar = np.random.rand(100, 2)   # x,y # lidar - Light Detection and Ranging
  camera = np.random.rand(100, 1)  # jasność
  radar = np.random.rand(100, 1)   # prędkość
  ```
* Połącz je kolumnowo w macierz `X` o kształcie `(100,4)`.
* Podziel `X` na `train` (80%) i `test` (20%) (np. `np.array_split` lub indeksowanie).
* Oblicz średnią jasność i średnią prędkość dla obu zestawów.

**Pytanie kontrolne:** Dlaczego warto przetasować dane (shuffle) przed splitem w prawdziwym pipeline?

In [ ]:
import numpy as np

lidar = np.random.rand(100, 2)   # x,y
camera = np.random.rand(100, 1)  # jasność
radar = np.random.rand(100, 1)   # prędkość

X = np.hstack([lidar, camera, radar])
assert X.shape == (100, 4)

# split train/test (bez shuffle dla prostoty)
n_train = int(X.shape[0] * 0.8)
train, test = np.array_split(X, [n_train])

# indeksy kolumn: camera -> 2, radar -> 3 (0-based)
mean_camera_train = train[:, 2].mean()
mean_radar_train = train[:, 3].mean()
mean_camera_test = test[:, 2].mean()
mean_radar_test = test[:, 3].mean()

print("X.shape:", X.shape)
print("train/test shapes:", train.shape, test.shape)
print("mean camera train/test:", mean_camera_train, mean_camera_test)
print("mean radar train/test:", mean_radar_train, mean_radar_test)

X.shape: (100, 4)
train/test shapes: (80, 4) (20, 4)
mean camera train/test: 0.4979756272875943 0.4328998934890057
mean radar train/test: 0.5023572109683373 0.5222199695372245


## 7. NumPy vs. czysty Python

**Kontekst:** NumPy działa o wiele szybciej niż pętle Pythonowe dla operacji numerycznych. Tu wykorzystamy `np.linspace`.

**Polecenie**

* Stwórz `x = np.linspace(0, 1, 10_000_000)`.
* Oblicz `s = sin(x)**2 + cos(x)**2`:

  * a) w czystym Pythonie (pętla `for` i `math.sin`, `math.cos`)
  * b) w NumPy (`np.sin`, `np.cos` — wektoryzacja)
* Porównaj czasy wykonania (wskazane: `%timeit` w notebooku lub `time.time()`).

In [ ]:
import numpy as np
import math
import time

# dane
x = np.linspace(0, 1, 10_000_000)

# NumPy version
t0 = time.time()
y_np = np.sin(x) ** 2 + np.cos(x) ** 2
t_np = time.time() - t0

# Python loop version (bardzo wolne; uruchamiaj ostrożnie; jak trwa dłuej ni 15s, to przerwij i zmniejsz przykład)
t0 = time.time()
s = 0.0
for xi in x:
    s += math.sin(xi) ** 2 + math.cos(xi) ** 2
t_py = time.time() - t0

print(f"NumPy time: {t_np:.3f}s")
print(f"Pure Python loop time: {t_py:.3f}s")

NumPy time: 0.281s
Pure Python loop time: 5.447s


## 8. Copy, View

**Kontekst:** Podczas preprocessingu zespoły czasami pracują na tym samym obiekcie myśląc, że mają kopię — to prowadzi do skażenia danych.

**Polecenie**

* Stwórz `patients = np.random.randint(60, 120, (5, 4))`.
  * `doctors_view`, gdzie doktor będzie przeglądał tylko co drugi pomiar,
  * `research_copy`, czyli kopię patients.
* Lekarz przez pomyłkę wykona `doctors_view[:] = -1`.
* Sprawdź, czy `patients` się zmieniło i czy `research_copy` pozostało bez zmian. Wyjaśnij.

**Pytanie kontrolne:** W jaki sposób zabezpieczyć workflow, żeby przypadkowe zmiany nie wpływały na bazę danych?

In [ ]:
import numpy as np

patients = np.random.randint(60, 120, (5, 4))
doctors_view = patients[:, ::2]
research_copy = patients.copy()

print("przed zmiana:\n", patients)
doctors_view[:] = -1
print("po zmianie doctors_view:\n", patients)
print("research_copy (czy zmienione?):\n", research_copy)

# wykrywamy, które są view / copy
print("doctors_view.base is patients?", doctors_view.base is patients)
print("research_copy.base is patients?", research_copy.base is patients)

przed zmiana:
 [[ 70 103  85 107]
 [ 62  96  91  87]
 [ 77 118  95  89]
 [ 97  80 108 111]
 [ 74  83  86 112]]
po zmianie doctors_view:
 [[ -1 103  -1 107]
 [ -1  96  -1  87]
 [ -1 118  -1  89]
 [ -1  80  -1 111]
 [ -1  83  -1 112]]
research_copy (czy zmienione?):
 [[ 70 103  85 107]
 [ 62  96  91  87]
 [ 77 118  95  89]
 [ 97  80 108 111]
 [ 74  83  86 112]]
doctors_view.base is patients? True
research_copy.base is patients? False


## 9. Jak CNN „przesuwa okno” po obrazie?

**Kontekst:** W konwolucyjnej sieci neuronowej filtr (np. 3×3) „przesuwa się” po obrazie piksel po pikselu. Parametr stride określa, o ile pikseli filtr przesuwa się w pamięci między kolejnymi pozycjami. Zrozumienie, jak numpy.strides działa, pozwala intuicyjnie pojąć, dlaczego operacja konwolucji może być wydajna bez kopiowania danych.

**Polecenie**

1. Utwórz: `A = np.arange(1,13).reshape(3,4)` — traktuj jako obraz `3 × 4`, oraz `AT = A.T`.
2. Wypisz: `A`, `A.strides`, `AT`, `AT.strides`.
3. Oblicz ile bajtów trzeba przeskoczyć, aby dotrzeć:
   * od `A[0,0]` do `A[0,1]`,
   * od `A[0,0]` do `A[1,0]`.
4. Sprawdź, czy `AT` jest widokiem (`AT.base is A`), zmień `A[0,0] = -99` i sprawdź `AT`.
5. Napisz funkcję `memory_offset(A, i, j)`, która obliczy ile bajtów trzeba przejść od `A[0][0]` do miejsca `A[i][j]`
   Użyj jej, żeby policzyć offsety kilku elementów w `A` i `A.T`. Zinterpretuj wyniki.

**Pytanie kontrolne:** Wyjaśnij własnymi słowami: co się stanie jak zmienisz `strides`?

In [ ]:
import numpy as np

A = np.arange(1, 13).reshape(3, 4)
print("A:\n", A)
print("A.strides:", A.strides)

AT = A.T
print("AT:\n", AT)
print("AT.strides:", AT.strides)

# elementsize (liczba bajtów na element)
bs = A.itemsize
print("itemsize (bajtów per element):", bs)

# obliczenia ręczne:
offset_A_00_to_01 = bs
offset_A_00_to_10 = A.shape[1] * bs
print("offset A[0,0] -> A[0,1] (bajtów):", offset_A_00_to_01)
print("offset A[0,0] -> A[1,0] (bajtów):", offset_A_00_to_10)

# sprawdzenie widoku
print("A.T.base is A ?", AT.base is A)

# zmiana A i obserwacja AT
A[0,0] = -99
print("A po zmianie:\n", A)
print("A.T po zmianie:\n", AT)

# funkcja memory_offset
def memory_offset(M, i, j):
    return M.strides[0] * i + M.strides[1] * j

print("memory offset A[2,3]:", memory_offset(A, 2, 3))
print("memory offset AT[2,3]:", memory_offset(AT, 2, 3))

A:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
A.strides: (32, 8)
AT:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
AT.strides: (8, 32)
itemsize (bajtów per element): 8
offset A[0,0] -> A[0,1] (bajtów): 8
offset A[0,0] -> A[1,0] (bajtów): 32
A.T.base is A ? False
A po zmianie:
 [[-99   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
A.T po zmianie:
 [[-99   5   9]
 [  2   6  10]
 [  3   7  11]
 [  4   8  12]]
memory offset A[2,3]: 88
memory offset AT[2,3]: 112


## 10. ⭐️ Zaawansowana augmentacja i analiza obrazów RGB

**Kontekst:** Przy trenowaniu CNN operujemy na obrazach RGB. Często robimy augmentacje (jasność, kontrast, rotacje, przesunięcia) i porównujemy obrazy np. za pomocą **cosine similarity**. Trzeba uważać, które operacje zwracają **widok**, a które **kopię**, aby nie psuć danych przez przypadek.

**Polecenie**

1. Wygeneruj **10 losowych obrazów RGB**, każdy o wymiarach `32×32×3` z wartościami `uint8` (0–255).
2. Napisz funkcję `cosine_similarity(img1, img2)`, która oblicza podobieństwo kosinusowe między dwoma obrazami traktowanymi jako wektory.
3. Stwórz funkcję `augment(img)` która tworzy warianty obrazu:

   * oryginał,
   * flip poziomy,
   * flip pionowy,
   * rotacja 90°,
   * jaśniejsza wersja,
   * wersja z większym kontrastem,
   * mały przesunięty fragment (crop + pad),
   * zamiana kanałów RGB na BGR.
4. Dla każdego wariantu sprawdź, które są **widokiem**, a które **kopią** (`.base`).
5. Oblicz macierz podobieństwa kosinusowego między wszystkimi 10 obrazami oryginalnymi i wypisz średnie podobieństwo.
6. Oblicz podobieństwo między oryginałami a ich wariantami i sprawdź, które operacje najbardziej zmieniają obraz (najmniejsze cosine similarity).   

In [ ]:
# Uzupełnij

## 11. ⭐️ Świadome kopiowanie

**Kontekst**
Pracujesz z dużymi macierzami w Pythonie/NumPy, które reprezentują np. wyniki eksperymentów, symulacje lub dane użytkowników.

**Polecenie**
Twoim zadaniem jest zdecydować w jaki sposób należy **modyfikować dane**, w miejscu, w kopii, czy wystarczy widok? A może trzeba użyć deepcopy? Rozważ dwa przypadki - kiedy używasz biblioteki `numpy` i `copy`. Odpowiedz na wszystkie pytania. W każdej części musisz **uzasadnić wybór metody**.

Na początku stwórz dwuwymiarową tablicę `M`, na której będziesz demonstrować i uzasadniać użycie wybranej metody.

#### **a) Lokalna korekta**

Wartość w komórce `[0,0]` jest błędna i powinna być `1`.

* Jak poprawisz tę wartość?
* Czy zmieniasz oryginał, czy tworzysz kopię?
* Jak działa pamięć w tym przypadku?

#### **b) Alternatywna wersja danych**

Chcesz stworzyć **zmodyfikowaną wersję danych**, np. w kolumnie 2 przeskalować wszystkie wartości, w celu przeprowadzenia eksperymentu.

* Zastanów się, czy potrzebujesz `view`, `copy` czy `deepcopy`.
* Przetestuj różne podejścia (`M.view()`, `M.copy()`) i sprawdź, co się dzieje po modyfikacji nowej macierzy.

#### **c) Symulacje z listą zagnieżdżoną**

Tworzysz listę eksperymentów:

```python
L = [M, M.copy()]
```

Teraz chcesz **przeprowadzić symulacje zmian**, np. dodając losowe wartości, **bez zmiany oryginału** ani kopii w `L`.

* Jakiego rodzaju kopiowania użyjesz?
* Co się stanie, jeśli użyjesz tylko `copy` zamiast `deepcopy`, gdy struktura jest zagnieżdżona?

#### **d) Podzbiór kolumn**

Wybierasz podzbiór kolumn np. 1 i 3:

```python
subset = M[:, [1, 3]]
```

* Sprawdź, czy zmiany w `subset` wpływają na `M`.
* Porównaj to z cięciem typu `subset = M[:, 1:3]`.